// Where the four samples are, and whether they are there.
//
// **The bytes are the Apple app's, copied rather than referenced.** They are
// generated by `apple/Sounds/generate.py` and by nothing else — "there is no
// third-party audio in the app, nothing to attribute, and no file anybody has to
// trust" — and the four files under `Sounds/` here are byte-identical to the
// four under `apple/MiniXiangqi/Sounds/`. The Windows CI job checks that with a
// hash comparison, so a retune that reaches one bundle and not the other fails
// loudly rather than leaving the same board sounding different on two platforms.
//
// They are copied because a `<None Include="..\..\apple\...">` would make the
// Windows build depend on the Apple app's own directory layout, and the two
// frontends are deliberately disjoint trees worked on in parallel — a rename
// over there would break a build over here for no reason anybody could see from
// either side. The generator stays the single source; the two bundles are both
// its outputs, and the hash check is what says so mechanically.
//
// Nothing here plays anything. `MiniXiangqi.App`'s `BoardSoundPlayer` is what
// makes a noise, for the reason everything in this project's frontend split has:
// a WinUI 3 process cannot be launched over SSH, and the harness has to be able
// to state that the four samples reached the output directory on a machine with
// no audio device at all.

using System.Buffers.Binary;

namespace MiniXiangqi.Play;

public static class BoardSoundAssets
{
    /// <summary>
    /// The directory the four samples are copied into beside every executable
    /// that carries them — the app and the harness alike.
    /// </summary>
    public static string Directory { get; } = Path.Combine(AppContext.BaseDirectory, "sounds");

    /// <summary>The file this voice is carried by, whether or not it is there.</summary>
    public static string PathFor(BoardSound sound) =>
        Path.Combine(Directory, sound.Resource() + ".wav");

    /// <summary>
    /// The samples the code names and the build did not deliver.
    ///
    /// It exists for the same reason the Apple <c>BoardSounds.missing</c> does:
    /// a sample that fell out of the bundle is caught by a harness that can say
    /// so rather than by a board that has gone quiet, since sound is never the
    /// only way anything is conveyed and a missing file is therefore invisible in
    /// use.
    /// </summary>
    public static IReadOnlyList<BoardSound> Missing =>
        [.. BoardSounds.All.Where(sound => !File.Exists(PathFor(sound)))];

    /// <summary>
    /// How long a sample runs, or null where the file is absent or is not the
    /// uncompressed WAV the generator writes.
    ///
    /// This is <c>BoardSounds.duration(of:)</c>'s counterpart, and it is here for
    /// its reason: it holds the accepted character — short, and the conclusion
    /// the only one that is a gesture — to a number the harness can check. It
    /// reads the header rather than decoding anything, because the four files are
    /// 16-bit PCM mono at 44.1 kHz by construction and the duration of a PCM
    /// stream is arithmetic over its own header.
    /// </summary>
    public static TimeSpan? DurationOf(BoardSound sound)
    {
        byte[] header;
        try
        {
            using FileStream file = File.OpenRead(PathFor(sound));
            header = new byte[Math.Min(file.Length, 4096)];
            if (file.ReadAtLeast(header, header.Length, throwOnEndOfStream: false) < 44)
            {
                return null;
            }
        }
        catch (Exception failure) when (
            failure is IOException or UnauthorizedAccessException)
        {
            return null;
        }

        ReadOnlySpan<byte> bytes = header;
        if (!bytes[..4].SequenceEqual("RIFF"u8) || !bytes[8..12].SequenceEqual("WAVE"u8))
        {
            return null;
        }

        // The chunk walk, rather than an assumption that `fmt ` and `data` sit at
        // the canonical offsets: a WAV is a chunked format and a writer is
        // entitled to put something else in between.
        int channels = 0;
        int rate = 0;
        int bits = 0;
        for (int at = 12; at + 8 <= bytes.Length;)
        {
            ReadOnlySpan<byte> id = bytes.Slice(at, 4);
            uint size = BinaryPrimitives.ReadUInt32LittleEndian(bytes.Slice(at + 4, 4));
            int body = at + 8;

            if (id.SequenceEqual("fmt "u8) && body + 16 <= bytes.Length)
            {
                channels = BinaryPrimitives.ReadUInt16LittleEndian(bytes.Slice(body + 2, 2));
                rate = (int)BinaryPrimitives.ReadUInt32LittleEndian(bytes.Slice(body + 4, 4));
                bits = BinaryPrimitives.ReadUInt16LittleEndian(bytes.Slice(body + 14, 2));
            }
            else if (id.SequenceEqual("data"u8))
            {
                int frame = channels * (bits / 8);
                return frame > 0 && rate > 0
                    ? TimeSpan.FromSeconds((double)size / (frame * rate))
                    : null;
            }

            // Chunks are word-aligned: an odd size is followed by a pad byte.
            at = body + (int)size + ((size & 1) == 1 ? 1 : 0);
        }

        return null;
    }
}
