// What the board is heard to do: the four voices, the rule that chooses among
// them, and the switch in front of them.
//
// docs/interaction-design.md, "Sound and haptics" and "Board play": the board
// plays **one sound per landing**, chosen by what the landing means, and the
// four are a plain arrival, a capture, a check and the game's conclusion. Where
// a landing answers to more than one, the higher meaning is the only one heard —
// conclusion, then capture, then check, then the plain landing. Nothing sounds
// for an illegal tap, a refusal, a selection or a flip, and the samples
// themselves are apple/Sounds/generate.py's, unchanged.
//
// **This file is the whole of the decision and none of the playing.** The rule
// below is a pure function of what arrived, so MiniXiangqi.Smoke can play a game
// and state which event asked for which voice on a machine with no audio device
// and nobody logged in; MiniXiangqi.App holds the thing that actually makes a
// noise. That is the same split as everything else in this frontend, for the
// same reason — the felt-and-heard separation the contracts define has a checked
// half and a heard half, and only one of them can be run headlessly. The heard
// half is the owner's tour.
//
// **There is no felt half on Windows.** The Apple `Feedback` carries an `Event`
// vocabulary beside its `Sound` one, because a Mac trackpad and an iPhone's
// engine can answer a touch. Windows offers no equivalent — `Windows.Devices.Haptics`
// speaks to pens and game controllers, not to the machine the app is running on
// — and the contract's rule for hardware that is not there is that the row is
// **removed rather than greyed out**, "unavailable rather than silently
// ineffective". So 触感 is absent from this platform's Settings destination and
// nothing here has a pattern to perform. `haptics.enabled` is neither read nor
// written: whatever an Apple frontend stored under it survives untouched.

namespace MiniXiangqi.Play;

/// <summary>
/// What is heard. One per landing and never more, chosen by what the landing
/// means rather than by how often it happens.
///
/// Every case is an event of the *board*. There is nothing here for an illegal
/// tap, a refusal, a selection or a flip: sound reinforces meaning, and
/// answering a learner's exploratory tap with a noise would scold it.
/// </summary>
public enum BoardSound
{
    /// <summary>A disc meeting the board. The one every move makes.</summary>
    Plain,

    /// <summary>The same landing with mass behind it.</summary>
    Capture,

    /// <summary>The landing, plus the accent that sounds with the check rings.</summary>
    Check,

    /// <summary>
    /// The game settling — a result, however it was reached, including the draw
    /// a player claims and the resignation, neither of which moves a piece at
    /// all.
    /// </summary>
    Conclusion,
}

public static class BoardSounds
{
    /// <summary>The four, in the order the precedence rule ranks them.</summary>
    public static readonly BoardSound[] All =
        [BoardSound.Conclusion, BoardSound.Capture, BoardSound.Check, BoardSound.Plain];

    /// <summary>
    /// The sample this voice is carried by. Generated by
    /// <c>apple/Sounds/generate.py</c> and by nothing else; the prefix keeps the
    /// four together, exactly as it does in the Apple app's own bundle.
    /// </summary>
    public static string Resource(this BoardSound sound) => sound switch
    {
        BoardSound.Capture => "board-capture",
        BoardSound.Check => "board-check",
        BoardSound.Conclusion => "board-conclusion",
        _ => "board-plain",
    };

    /// <summary>
    /// What a landing sounds like: one sound, chosen by what has arrived rather
    /// than by what was pressed, in the accepted order of precedence.
    ///
    /// <list type="bullet">
    /// <item>The game being over outranks everything, and **replaces** the
    /// landing sound rather than joining it: a result is the last thing that
    /// happened, and a tock underneath it would be the move competing with its
    /// own consequence.</item>
    /// <item>A capture outranks a check, because the take is the louder fact and
    /// the check has the rings, the 将军 token and the status line saying it as
    /// well.</item>
    /// <item>Everything else is the plain tock, a move taken back included:
    /// reversing a move is a disc landing on a point, and a sound played
    /// backwards would be a fifth thing to learn for an action the board already
    /// shows in reverse.</item>
    /// </list>
    ///
    /// It describes the position that arrived rather than the action that
    /// produced it, which is why one rule serves a played move, the machine's
    /// reply and an Undo alike. <paramref name="captured"/> is a *move's* take
    /// and never an Undo's restoration: a disc coming back is a restoration, not
    /// a capture, which is exactly the distinction the Apple rule draws by asking
    /// whether the fading disc belonged to a move.
    /// </summary>
    public static BoardSound OfTheLanding(bool captured, bool finished, bool inCheck)
    {
        if (finished)
        {
            return BoardSound.Conclusion;
        }

        if (captured)
        {
            return BoardSound.Capture;
        }

        return inCheck ? BoardSound.Check : BoardSound.Plain;
    }
}

/// <summary>
/// The heard half of the board's feedback, with 声音 in front of it.
///
/// The gate is read **at the moment the sound would fire** rather than when this
/// was composed, which is the rule every preference in this frontend shares: a
/// switch takes effect on the next landing, not on the next run. The composition
/// lives here, in front of any particular player, so that the harness can hold
/// the app's own gate over a recorder and see exactly what the app would have
/// silenced.
/// </summary>
public sealed class Feedback
{
    private readonly Action<BoardSound> _play;

    private Feedback(Action<BoardSound> play) => _play = play;

    /// <summary>
    /// A board that is not heard at all. It is the default everywhere a caller
    /// supplies nothing — the render harness, and every harness section whose
    /// claim is not about sound — because a board with no player attached is a
    /// quiet board and not a broken one.
    /// </summary>
    public static readonly Feedback Silent = new(_ => { });

    /// <summary>
    /// The board heard through <paramref name="play"/>, whenever 声音 says so.
    /// </summary>
    public static Feedback Gating(IPreferenceStore preferences, Action<BoardSound> play) =>
        new(sound =>
        {
            if (Preferences.Sound(preferences))
            {
                play(sound);
            }
        });

    /// <summary>
    /// Reports a landing. Called when the event **completes** — a move sounds
    /// when the piece lands, never when it lifts — which on this platform is the
    /// instant the core has committed it and the board has been re-read, since a
    /// Windows move is drawn without travel until the appearance pass gives it
    /// one.
    /// </summary>
    public void Play(BoardSound sound) => _play(sound);
}
