#!/usr/bin/env python3
"""The board's four sounds, synthesized here rather than sourced.

docs/interaction-design.md, "Sound and haptics": the board plays one sound per
landing, chosen by what the landing means — a plain arrival, a capture, a check,
or the conclusion of the game. Those four samples are generated by this script
and by nothing else, which is the point: there is no third-party audio in the
app, nothing to attribute, and no file anybody has to trust. Re-tuning is a
parameter edit below followed by one run, and the result is byte-identical on
any machine — the only randomness is a filtered noise burst from a fixed seed.

    python3 apple/Sounds/generate.py

writes the four WAVs into apple/MiniXiangqi/Sounds/, where the app target's
synchronized group picks them up as resources, and prints what it wrote: the
duration, peak, and spectral measurements that the accepted character — short,
dark, percussive, quiet, nothing melodic — is judged against. The final word on
all of it is the owner's ear against the running app; these numbers only keep a
tuning pass honest about what it changed.

The recipe is the same physical story in each: a struck wooden body, which is a
handful of exponentially decaying modes, plus the noise of the contact itself,
lowpassed so no edge of it is shrill. What separates the four is pitch, decay,
and the one added accent — never a melody, because a sequence of pitches reads
as interface candy rather than as a board.
"""

import cmath
import math
import random
import struct
import wave
from pathlib import Path

SAMPLE_RATE = 44100
"""Ordinary CD rate. These are tiny files; nothing is bought by going lower, and
the 6 kHz ceiling below is measured against a spectrum with room above it."""

SEED = 20260728
"""Fixed, so two runs of this script produce the same bytes. Which seed it is
does not matter; that it never changes does."""

CEILING_HZ = 6000.0
"""Nothing prominent above this. Every sound leaves through a lowpass at it, and
the report prints how much energy is left over the line."""

# The four sounds, as parameters. Each is a body — modes of (frequency in Hz,
# decay time constant in seconds, relative amplitude) — plus the contact noise,
# an envelope attack, and the peak the finished file is normalized to. Amplitudes
# are relative to each other; the peak is what sets the level in the app.
SOUNDS = {
    # A disc meeting the board. The dominant sound of a real set, so it is the
    # quietest thing here that can still be heard under the landing haptic: it
    # happens on every single move.
    "board-plain": {
        "duration": 0.110,
        "modes": [(390.0, 0.030, 1.00), (935.0, 0.016, 0.45), (1580.0, 0.007, 0.20)],
        "noise": {"amplitude": 0.55, "decay": 0.0045, "cutoff": 2100.0},
        "attack": 0.0015,
        "peak": 0.20,
    },
    # A take is a landing with mass: the same body struck lower and left to ring
    # a little longer, and a shade louder than the plain tock.
    "board-capture": {
        "duration": 0.145,
        "modes": [(281.0, 0.042, 1.00), (673.0, 0.022, 0.45), (1138.0, 0.010, 0.20)],
        "noise": {"amplitude": 0.50, "decay": 0.0060, "cutoff": 1500.0},
        "attack": 0.0015,
        "peak": 0.26,
    },
    # The plain tock with one brighter transient a few milliseconds behind it,
    # sounding with the check rings' pulse. It is an accent on the landing, not
    # an alarm: higher than the body, and a third of its level.
    "board-check": {
        "duration": 0.130,
        "modes": [(390.0, 0.030, 1.00), (935.0, 0.016, 0.45), (1580.0, 0.007, 0.20)],
        "accent": [(2450.0, 0.014, 0.30), (3300.0, 0.008, 0.12)],
        "accent_delay": 0.006,
        "noise": {"amplitude": 0.55, "decay": 0.0045, "cutoff": 2100.0},
        "attack": 0.0015,
        "peak": 0.21,
    },
    # The game settling. Low, soft-edged — a twenty-millisecond rise rather than
    # a strike — and the only one long enough to be a gesture instead of a hit.
    # One sound for every result: which result it was is on the screen, in words.
    "board-conclusion": {
        "duration": 0.420,
        "modes": [(128.0, 0.150, 1.00), (192.0, 0.105, 0.42), (256.0, 0.070, 0.18)],
        "noise": {"amplitude": 0.10, "decay": 0.030, "cutoff": 700.0},
        "attack": 0.020,
        "cutoff": 1400.0,
        "peak": 0.22,
    },
}


# MARK: - The parts


def envelope(count, decay, attack):
    """The shape every layer wears: a raised-cosine rise, then an exponential
    fall. The rise exists so the first sample is not a step — a step is a click
    of its own, and a click at the top of a tock is exactly the shrillness the
    accepted character rules out."""
    shape = []
    for index in range(count):
        time = index / SAMPLE_RATE
        rise = 1.0 if time >= attack else 0.5 - 0.5 * math.cos(math.pi * time / attack)
        shape.append(rise * math.exp(-time / decay))
    return shape


def mode(count, frequency, decay, amplitude, attack, delay=0.0):
    """One resonant mode of the struck body."""
    layer = [0.0] * count
    start = int(delay * SAMPLE_RATE)
    for index, level in enumerate(envelope(count - start, decay, attack)):
        time = index / SAMPLE_RATE
        layer[start + index] = amplitude * level * math.sin(2 * math.pi * frequency * time)
    return layer


def contact(count, amplitude, decay, cutoff, rng):
    """The noise of the strike itself, lowpassed before it is shaped: what is
    wanted is the thud of two wooden things meeting, not a hiss."""
    filtered = lowpass([rng.uniform(-1.0, 1.0) for _ in range(count)], cutoff)
    shape = envelope(count, decay, attack=0.0005)
    return [amplitude * sample * level for sample, level in zip(filtered, shape)]


def lowpass(samples, cutoff, poles=2):
    """A one-pole RC lowpass run `poles` times over the buffer. Gentle, and
    gentle is right: the point is to take the edge off, not to draw a wall."""
    alpha = 1.0 - math.exp(-2.0 * math.pi * cutoff / SAMPLE_RATE)
    out = list(samples)
    for _ in range(poles):
        value = 0.0
        for index, sample in enumerate(out):
            value += alpha * (sample - value)
            out[index] = value
    return out


def taper(samples, seconds=0.004):
    """The last few milliseconds ramped to silence, so the file does not end on
    a discontinuity the speaker would answer with a tick of its own."""
    count = min(int(seconds * SAMPLE_RATE), len(samples))
    for index in range(count):
        samples[len(samples) - count + index] *= 1.0 - index / count
    return samples


def normalize(samples, peak):
    """To an absolute peak, not to full scale: the level is a design decision —
    quieter than the system alert sound — and it lives here, in one number per
    sound, rather than in a volume set at playback."""
    loudest = max(abs(sample) for sample in samples) or 1.0
    return [sample * peak / loudest for sample in samples]


def build(spec):
    rng = random.Random(SEED)
    count = int(spec["duration"] * SAMPLE_RATE)
    attack = spec["attack"]
    layers = [mode(count, frequency, decay, amplitude, attack)
              for frequency, decay, amplitude in spec["modes"]]
    layers += [mode(count, frequency, decay, amplitude, attack=0.0008,
                    delay=spec["accent_delay"])
               for frequency, decay, amplitude in spec.get("accent", [])]
    layers.append(contact(count, rng=rng, **spec["noise"]))
    mixed = [sum(values) for values in zip(*layers)]
    return normalize(taper(lowpass(mixed, spec.get("cutoff", CEILING_HZ))), spec["peak"])


def write(path, samples):
    frames = b"".join(struct.pack("<h", int(max(-1.0, min(1.0, sample)) * 32767))
                      for sample in samples)
    with wave.open(str(path), "wb") as file:
        file.setnchannels(1)
        file.setsampwidth(2)
        file.setframerate(SAMPLE_RATE)
        file.writeframes(frames)


# MARK: - The report
#
# Measurement only: nothing below shapes a sound. It exists so that a tuning pass
# can see what it did to the level and the spectrum without opening an editor,
# and so the accepted character has numbers attached to it.


def spectrum(samples):
    """Magnitudes of the whole sound, from a radix-2 FFT over the next power of
    two. Written out here rather than imported: this script depends on the
    standard library alone, so that generating the assets needs nothing
    installed."""
    size = 1 << (len(samples) - 1).bit_length()
    padded = [complex(sample) for sample in samples] + [0j] * (size - len(samples))

    def transform(values):
        length = len(values)
        if length == 1:
            return values
        even = transform(values[0::2])
        odd = transform(values[1::2])
        factors = [cmath.exp(-2j * math.pi * index / length) * odd[index]
                   for index in range(length // 2)]
        return ([even[index] + factors[index] for index in range(length // 2)]
                + [even[index] - factors[index] for index in range(length // 2)])

    bins = transform(padded)[: size // 2]
    return [abs(value) for value in bins], SAMPLE_RATE / size


def report(name, samples):
    magnitudes, resolution = spectrum(samples)
    power = [magnitude * magnitude for magnitude in magnitudes]
    total = sum(power) or 1.0
    centroid = sum(index * resolution * value for index, value in enumerate(power)) / total
    above = sum(value for index, value in enumerate(power)
                if index * resolution > CEILING_HZ) / total
    peak = max(abs(sample) for sample in samples)
    rms = math.sqrt(sum(sample * sample for sample in samples) / len(samples))
    decibels = lambda value: 20 * math.log10(value) if value > 0 else float("-inf")
    print(f"  {name:<18} {len(samples) / SAMPLE_RATE * 1000:6.1f} ms"
          f"   peak {decibels(peak):6.1f} dBFS"
          f"   rms {decibels(rms):6.1f} dBFS"
          f"   centroid {centroid:6.0f} Hz"
          f"   above {CEILING_HZ / 1000:.0f} kHz {above * 100:5.2f}%")


def main():
    directory = Path(__file__).resolve().parent.parent / "MiniXiangqi" / "Sounds"
    directory.mkdir(parents=True, exist_ok=True)
    print(f"writing {len(SOUNDS)} sounds to {directory}")
    for name, spec in SOUNDS.items():
        samples = build(spec)
        write(directory / f"{name}.wav", samples)
        report(name, samples)


if __name__ == "__main__":
    main()
