// The four samples, loaded once and kept ready to sound.
//
// docs/interaction-design.md, "Sound and haptics": the board's sounds are short
// and reinforce meaning, and none of them is the only channel for anything. The
// assets are generated by apple/Sounds/generate.py and carry their own level —
// nothing here adjusts volume, so retuning is one number in that script rather
// than a number in each of two places.
//
// A player per sound, primed at construction. Priming is the whole reason this
// type exists: an AVAudioPlayer built at the moment of the landing has its file
// to open and its buffers to allocate first, and the tock would arrive after the
// disc did. These open at the play screen's construction instead, when nothing
// is waiting on them.

import AVFoundation

final class BoardSounds {
    private var players: [Feedback.Sound: AVAudioPlayer] = [:]

    /// Loads every sound the code names. A missing or unreadable one is left
    /// out rather than raised: sound is never the only way anything is
    /// conveyed, so a board that cannot find its samples is a quiet board and
    /// not a broken one. `missing` is what the tests read, so a sample that
    /// fell out of the bundle is caught there rather than by silence.
    init(bundle: Bundle = .main) {
        for sound in Feedback.Sound.allCases {
            guard let url = bundle.url(forResource: sound.resource, withExtension: "wav"),
                  let player = try? AVAudioPlayer(contentsOf: url) else { continue }
            player.prepareToPlay()
            players[sound] = player
        }
    }

    /// The sounds that were named and not found.
    var missing: [Feedback.Sound] {
        Feedback.Sound.allCases.filter { players[$0] == nil }
    }

    /// How long a sound runs, for the tests that hold the accepted character —
    /// short, and the conclusion the only one that is a gesture — to a number.
    func duration(of sound: Feedback.Sound) -> TimeInterval? {
        players[sound]?.duration
    }

    /// Rewound before it is started, so a sound that is still ringing from the
    /// previous landing restarts rather than being ignored. One player per
    /// sound is enough for a board where one thing lands at a time; two moves
    /// cannot overlap, because a committing transition runs to completion.
    func play(_ sound: Feedback.Sound) {
        guard let player = players[sound] else { return }
        player.currentTime = 0
        player.play()
    }
}
