// Feedback that is felt or heard, at the two moments the contract names.
//
// docs/interaction-design.md, "Motion and visual effects" and "Sound and
// haptics": feedback that reports an event fires when the event completes — a
// move sounds when the piece lands, not when it lifts — and feedback that
// answers a touch leads its animation. An illegal tap is a normal part of
// learning, so it takes the platform's lightest selection-weight feedback and
// never the warning pattern; on macOS the warning haptic does not exist at
// all, which satisfies that by construction. Haptics fire only where the
// hardware provides them — a Force Touch trackpad — and the system performer
// already honours the user's own trackpad setting.
//
// The two halves are separate because they answer to different rules and to
// different toggles. What is *felt* follows the touch and the arrival: two
// patterns, and every landing gets the same one. What is *heard* follows the
// meaning of what arrived: one sound per landing, chosen by the event, silent
// wherever the contract keeps it silent.
//
// Both toggles now exist: 声音 and 触感 are the second group of the Settings
// destination, and each half is gated by its own key at the moment it would
// fire. Neither gate knows about the other — sound off leaves a landing felt,
// haptics off leaves it heard.

#if os(macOS)
import AppKit
#endif
import Foundation

struct Feedback {
    /// What is felt.
    enum Event: Equatable {
        /// A disc arriving on its point — a move's or an Undo's.
        case landing
        /// The answer to a touch the game cannot act on: an illegal tap, or
        /// the acknowledgment beat.
        case acknowledgement
    }

    /// What is heard. One per landing and never more, chosen by what the
    /// landing means rather than by how often it happens: conclusion, then
    /// capture, then check, then the plain arrival. A capturing check is a
    /// capture — the take is the louder fact, and the rings say the rest.
    ///
    /// Every case is an event of the *board*. There is nothing here for an
    /// illegal tap, a refusal, a selection, or a flip: sound reinforces
    /// meaning, and answering a learner's exploratory tap with a noise would
    /// scold it. Those keep the lightest haptic and their answer on the board.
    enum Sound: String, CaseIterable, Equatable {
        /// A disc meeting the board. The one every move makes.
        case plain
        /// The same landing with mass behind it.
        case capture
        /// The landing, plus the accent that sounds with the check rings.
        case check
        /// The game settling — a result, however it was reached, including the
        /// draw a player claims without any piece moving at all.
        case conclusion

        /// The sample in the app bundle. Generated by `apple/Sounds/generate.py`
        /// and by nothing else; the prefix keeps the four together in a
        /// resource directory that has no folders.
        var resource: String { "board-\(rawValue)" }

        /// What a landing sounds like: one sound, chosen by what has arrived
        /// rather than by what was pressed, in the accepted order of
        /// precedence.
        ///
        /// - The game being over outranks everything, and replaces the landing
        ///   sound rather than joining it: a result is the last thing that
        ///   happened, and a tock underneath it would be the move competing
        ///   with its own consequence.
        /// - A capture outranks a check, because the take is the louder fact
        ///   and the check has the rings, the 将军 token, and the status line
        ///   saying it as well.
        /// - Everything else is the plain tock, a move taken back included:
        ///   reversing a move is a disc landing on a point, and a sound played
        ///   backwards would be a fifth thing to learn for an action the board
        ///   already animates in reverse.
        ///
        /// It reads the arrived position and the transit's own plan, both of
        /// which are settled before anything can arrive. A capture is the
        /// transit's fading disc — but only a move's, since a reversal's
        /// fading disc is the piece coming *back*, which is a restoration and
        /// not a take.
        ///
        /// One rule, and it describes a position rather than an action, which
        /// is why replay asks it the same question: a replayed landing is a
        /// landing, and the position it arrives at is finished or in check or
        /// neither exactly as a played one's is.
        static func ofTheLanding(_ transit: Transit?,
                                 finished: Bool,
                                 inCheck: Bool) -> Sound {
            if finished { return .conclusion }
            if transit?.kind == .move, transit?.fading != nil { return .capture }
            if inCheck { return .check }
            return .plain
        }
    }

    /// The half that is felt.
    var perform: (Event) -> Void
    /// The half that is heard.
    var play: (Sound) -> Void

    // MARK: - The two preferences

    /// Puts each accepted Settings switch in front of the half it governs, and
    /// reads it at the moment that half would fire rather than when this was
    /// composed: a switch takes effect on the next landing, not on the next run.
    /// What an absent key means belongs to `Preferences`, which every consumer of
    /// these preferences reads through — here it is enough that the answer is
    /// asked for again each time.
    ///
    /// The composition lives here, in front of any particular performer or
    /// player, so that a test can hold the app's own gates over a recorder and
    /// see exactly what the app would have silenced or stilled.
    static func gating(by defaults: UserDefaults = Preferences.defaults,
                       perform: @escaping (Event) -> Void,
                       play: @escaping (Sound) -> Void) -> Feedback {
        Feedback { event in
            guard Preferences.haptics.value(in: defaults) else { return }
            perform(event)
        } play: { sound in
            guard Preferences.sound.value(in: defaults) else { return }
            play(sound)
        }
    }

    // MARK: - The live feedback

    /// The hardware feedback, pattern chosen by what the event means:
    ///
    /// - `.alignment` for the landing, because Apple defines it for the moment
    ///   a dragged or moved object snaps into alignment — which is exactly a
    ///   disc settling onto a grid intersection. Performed at `.drawCompleted`
    ///   so the tap under the finger coincides with the drawn arrival.
    /// - `.generic` for the touch answer: the platform's unmarked, lightest
    ///   pattern, with none of `.levelChange`'s pressure semantics. Performed
    ///   `.now`, because the touch is what the player is waiting to feel
    ///   answered.
    ///
    /// The sounds are loaded and primed as this is built — at the play screen's
    /// construction, long before the first landing — so that the first tock is
    /// no later than the second.
    ///
    /// `NSHapticFeedbackManager` is AppKit, so the felt half described above is
    /// the macOS one — and the reason 触感 is offered there: the performer honours
    /// each machine's own trackpad and does nothing where there is no trackpad to
    /// tap, so the switch is never silently ineffective in a way the app would
    /// have to guess at. On iOS the felt half is deliberately silent for now:
    /// UIKit's feedback
    /// generators are a different shape — prepared ahead of the event rather
    /// than performed at a named time — and choosing their patterns is a
    /// design decision about a device that vibrates in the hand, not a
    /// translation of this one. Stage 6, which brings the iOS pass, owns it.
    /// Nothing is lost meanwhile: no feedback here is the only channel for
    /// anything, and the heard half is identical on both platforms.
    static let live: Feedback = {
        let sounds = BoardSounds()
        return gating { event in
            #if os(macOS)
            let performer = NSHapticFeedbackManager.defaultPerformer
            switch event {
            case .landing:
                performer.perform(.alignment, performanceTime: .drawCompleted)
            case .acknowledgement:
                performer.perform(.generic, performanceTime: .now)
            }
            #endif
        } play: { sound in
            sounds.play(sound)
        }
    }()
}
