// Feedback that is felt or heard, at the two moments the contract names.
//
// docs/interaction-design.md, "Motion and visual effects" and "Sound and
// haptics": feedback that reports an event fires when the event completes — a
// move sounds when the piece lands, not when it lifts — and feedback that
// answers a touch leads its animation. An illegal tap is a normal part of
// learning, so it takes the platform's lightest selection-weight feedback and
// never the warning pattern; on macOS the warning haptic does not exist at
// all, which satisfies that by construction. Haptics fire only where the
// hardware provides them — a Force Touch trackpad — and the system performer
// already honours the user's own trackpad setting.
//
// The two halves are separate because they answer to different rules and to
// different toggles. What is *felt* follows the touch and the arrival: two
// patterns, and every landing gets the same one. What is *heard* follows the
// meaning of what arrived: one sound per landing, chosen by the event, silent
// wherever the contract keeps it silent.

import AppKit
import Foundation

struct Feedback {
    /// What is felt.
    enum Event: Equatable {
        /// A disc arriving on its point — a move's or an Undo's.
        case landing
        /// The answer to a touch the game cannot act on: an illegal tap, or
        /// the acknowledgment beat.
        case acknowledgement
    }

    /// What is heard. One per landing and never more, chosen by what the
    /// landing means rather than by how often it happens: conclusion, then
    /// capture, then check, then the plain arrival. A capturing check is a
    /// capture — the take is the louder fact, and the rings say the rest.
    ///
    /// Every case is an event of the *board*. There is nothing here for an
    /// illegal tap, a refusal, a selection, or a flip: sound reinforces
    /// meaning, and answering a learner's exploratory tap with a noise would
    /// scold it. Those keep the lightest haptic and their answer on the board.
    enum Sound: String, CaseIterable, Equatable {
        /// A disc meeting the board. The one every move makes.
        case plain
        /// The same landing with mass behind it.
        case capture
        /// The landing, plus the accent that sounds with the check rings.
        case check
        /// The game settling — a result, however it was reached, including the
        /// draw a player claims without any piece moving at all.
        case conclusion

        /// The sample in the app bundle. Generated by `apple/Sounds/generate.py`
        /// and by nothing else; the prefix keeps the four together in a
        /// resource directory that has no folders.
        var resource: String { "board-\(rawValue)" }
    }

    /// The half that is felt.
    var perform: (Event) -> Void
    /// The half that is heard.
    var play: (Sound) -> Void

    // MARK: - The sound preference

    /// The accepted Settings toggle, per the Settings scope in product.md. The
    /// screen that offers it comes later; the preference it will write is
    /// honoured now, so that a user who turns sound off never has to wait for
    /// the toggle to be built twice.
    static let soundEnabledKey = "sound.enabled"

    /// Read at the moment a sound would play rather than cached at launch: a
    /// toggle takes effect on the next landing, not the next run. Absent — the
    /// state of every first launch — means on, because a board that says
    /// nothing until you visit Settings reads as a board with no sound.
    static func soundIsEnabled(in defaults: UserDefaults) -> Bool {
        defaults.object(forKey: soundEnabledKey) as? Bool ?? true
    }

    /// Puts the preference in front of the heard half, leaving the felt half
    /// alone: the haptics toggle is its own setting and is not this gate's
    /// business. The composition lives here, in front of any particular player,
    /// so that a test can hold the real gate over a recorder and see exactly
    /// what the app would have silenced.
    static func gatingSound(by defaults: UserDefaults = .standard,
                            perform: @escaping (Event) -> Void,
                            play: @escaping (Sound) -> Void) -> Feedback {
        Feedback(perform: perform) { sound in
            guard soundIsEnabled(in: defaults) else { return }
            play(sound)
        }
    }

    // MARK: - The live feedback

    /// The hardware feedback, pattern chosen by what the event means:
    ///
    /// - `.alignment` for the landing, because Apple defines it for the moment
    ///   a dragged or moved object snaps into alignment — which is exactly a
    ///   disc settling onto a grid intersection. Performed at `.drawCompleted`
    ///   so the tap under the finger coincides with the drawn arrival.
    /// - `.generic` for the touch answer: the platform's unmarked, lightest
    ///   pattern, with none of `.levelChange`'s pressure semantics. Performed
    ///   `.now`, because the touch is what the player is waiting to feel
    ///   answered.
    ///
    /// The sounds are loaded and primed as this is built — at the play screen's
    /// construction, long before the first landing — so that the first tock is
    /// no later than the second.
    static let live: Feedback = {
        let sounds = BoardSounds()
        return gatingSound { event in
            let performer = NSHapticFeedbackManager.defaultPerformer
            switch event {
            case .landing:
                performer.perform(.alignment, performanceTime: .drawCompleted)
            case .acknowledgement:
                performer.perform(.generic, performanceTime: .now)
            }
        } play: { sound in
            sounds.play(sound)
        }
    }()
}
