// Feedback that is felt or heard, at the two moments the contract names.
//
// docs/interaction-design.md, "Motion and visual effects" and "Sound and
// haptics": feedback that reports an event fires when the event completes — a
// move sounds when the piece lands, not when it lifts — and feedback that
// answers a touch leads its animation. An illegal tap is a normal part of
// learning, so it takes the platform's lightest selection-weight feedback and
// never the warning pattern; on macOS the warning haptic does not exist at
// all, which satisfies that by construction. Haptics fire only where the
// hardware provides them — a Force Touch trackpad — and the system performer
// already honours the user's own trackpad setting.
//
// The two halves are separate because they answer to different rules and to
// different toggles. What is *felt* follows the touch and the arrival: two
// patterns, and every landing gets the same one. What is *heard* follows the
// meaning of what arrived: one sound per landing, chosen by the event, silent
// wherever the contract keeps it silent.
//
// Both toggles now exist: 声音 and 触感 are the second group of the Settings
// destination, and each half is gated by its own key at the moment it would
// fire. Neither gate knows about the other — sound off leaves a landing felt,
// haptics off leaves it heard.
//
// The two events below are the whole of the felt vocabulary; which pattern each
// one takes on each platform, and whether the hardware is there to take it, are
// `Motion/Haptics.swift`'s.

import Foundation

struct Feedback {
    /// What is felt.
    enum Event: Equatable, CaseIterable {
        /// A disc arriving on its point — a move's or an Undo's.
        case landing
        /// The answer to a touch the game cannot act on: an illegal tap, or
        /// the acknowledgment beat.
        case acknowledgement
    }

    /// What is heard. One per landing and never more, chosen by what the
    /// landing means rather than by how often it happens: conclusion, then
    /// capture, then check, then the plain arrival. A capturing check is a
    /// capture — the take is the louder fact, and the rings say the rest.
    ///
    /// Every case is an event of the *board*. There is nothing here for an
    /// illegal tap, a refusal, a selection, or a flip: sound reinforces
    /// meaning, and answering a learner's exploratory tap with a noise would
    /// scold it. Those keep the lightest haptic and their answer on the board.
    enum Sound: String, CaseIterable, Equatable {
        /// A disc meeting the board. The one every move makes.
        case plain
        /// The same landing with mass behind it.
        case capture
        /// The landing, plus the accent that sounds with the check rings.
        case check
        /// The game settling — a result, however it was reached, including the
        /// draw a player claims without any piece moving at all.
        case conclusion
        /// A stone meeting the board. The placement games' one landing, and a
        /// sharper, smaller sound than the disc's: a stone is a harder, lighter
        /// thing than a wooden disc and it arrives without travelling.
        case stone

        /// The sample in the app bundle. Generated by `apple/Sounds/generate.py`
        /// and by nothing else; the prefix keeps the five together in a
        /// resource directory that has no folders.
        var resource: String { "board-\(rawValue)" }

        /// What a landing sounds like: one sound, chosen by what has arrived
        /// rather than by what was pressed, in the accepted order of
        /// precedence.
        ///
        /// - The game being over outranks everything, and replaces the landing
        ///   sound rather than joining it: a result is the last thing that
        ///   happened, and a tock underneath it would be the move competing
        ///   with its own consequence.
        /// - A capture outranks a check, because the take is the louder fact
        ///   and the check has the rings, the 将军 token, and the status line
        ///   saying it as well.
        /// - Everything else is the plain tock, a move taken back included:
        ///   reversing a move is a disc landing on a point, and a sound played
        ///   backwards would be a fifth thing to learn for an action the board
        ///   already animates in reverse.
        ///
        /// It reads the arrived position and the transit's own plan, both of
        /// which are settled before anything can arrive. A capture is the
        /// transit's fading disc — but only a move's, since a reversal's
        /// fading disc is the piece coming *back*, which is a restoration and
        /// not a take.
        ///
        /// One rule, and it describes a position rather than an action, which
        /// is why replay asks it the same question: a replayed landing is a
        /// landing, and the position it arrives at is finished or in check or
        /// neither exactly as a played one's is.
        /// `stone` says the landing was a stone placed rather than a disc
        /// arriving. It is a parameter rather than a fifth thing read off the
        /// transit because a placement builds no transit at all: nothing
        /// travels, so the landing is the commit itself.
        static func ofTheLanding(_ transit: Transit?,
                                 stone: Bool = false,
                                 finished: Bool,
                                 inCheck: Bool) -> Sound {
            if finished { return .conclusion }
            if transit?.kind == .move, transit?.fading != nil { return .capture }
            if inCheck { return .check }
            return stone ? .stone : .plain
        }
    }

    /// The half that is felt.
    var perform: (Event) -> Void
    /// The half that is heard.
    var play: (Sound) -> Void

    // MARK: - The two preferences

    /// Puts each accepted Settings switch in front of the half it governs, and
    /// reads it at the moment that half would fire rather than when this was
    /// composed: a switch takes effect on the next landing, not on the next run.
    /// What an absent key means belongs to `Preferences`, which every consumer of
    /// these preferences reads through — here it is enough that the answer is
    /// asked for again each time.
    ///
    /// The composition lives here, in front of any particular performer or
    /// player, so that a test can hold the app's own gates over a recorder and
    /// see exactly what the app would have silenced or stilled.
    static func gating(by defaults: UserDefaults = Preferences.defaults,
                       perform: @escaping (Event) -> Void,
                       play: @escaping (Sound) -> Void) -> Feedback {
        Feedback { event in
            guard Preferences.haptics.value(in: defaults) else { return }
            perform(event)
        } play: { sound in
            guard Preferences.sound.value(in: defaults) else { return }
            play(sound)
        }
    }

    // MARK: - The live feedback

    /// Both halves against real hardware, built once and held for the life of
    /// the app.
    ///
    /// Everything here is loaded and primed as this is built — at the play
    /// screen's construction, long before the first landing — so that the first
    /// tock is no later than the second and the first tap no later than the
    /// second. That is the whole reason the two performers are objects rather
    /// than calls: an `AVAudioPlayer` opened at the landing has its file to read
    /// first, and a feedback generator made at the landing has never been
    /// prepared.
    ///
    /// **The felt half is now real on both platforms.** It was macOS only until
    /// Stage 6, because UIKit's generators are a different shape from AppKit's
    /// performer — prepared ahead of the event rather than performed at a named
    /// time — and choosing their patterns was a design decision about a device
    /// that vibrates in the hand rather than a translation of this one. That
    /// decision is made in `Motion/Haptics.swift`, along with the question of
    /// whether the hardware is there at all.
    static let live: Feedback = {
        let sounds = BoardSounds()
        let haptics = HapticPerformer()
        return gating { event in
            haptics.perform(event)
        } play: { sound in
            sounds.play(sound)
        }
    }()
}
