// The four samples, held against what the app names and what it accepted.
//
// docs/interaction-design.md, "Sound and haptics": the board's sounds are
// short, and the conclusion is the only one long enough to be a gesture. The
// assets are generated by apple/Sounds/generate.py, so a sound that is missing
// from the bundle or has drifted out of its length is a slip in that script or
// in the target's resources — the kind of thing nobody notices from the app,
// because a board with no samples is simply a quiet board.

import Testing
@testable import MiniXiangqi

@Suite("The board's sounds")
@MainActor
struct BoardSoundsTests {

    @Test("Every sound the code names is in the bundle and loads")
    func everySoundLoads() {
        let sounds = BoardSounds()
        #expect(sounds.missing.isEmpty,
                "the app names five sounds and the bundle must carry all five")
        #expect(Feedback.Sound.allCases.count == 5)
    }

    @Test("A landing's sounds are short, and the conclusion is the one gesture")
    func lengthsMatchTheAcceptedCharacter() throws {
        let sounds = BoardSounds()
        for sound in [Feedback.Sound.plain, .capture, .check, .stone] {
            let duration = try #require(sounds.duration(of: sound))
            #expect(duration > 0)
            #expect(duration <= 0.150,
                    "a landing is an impact: \(sound.resource) runs \(duration) s")
        }
        // The stone is the sharper, smaller of the two landings — the accepted
        // proposal, ratified by ear, and pinned here so a re-tuning pass cannot
        // quietly make it the disc's equal.
        let stone = try #require(sounds.duration(of: .stone))
        let disc = try #require(sounds.duration(of: .plain))
        #expect(stone < disc, "a stone lets go faster than a wooden disc")
        let conclusion = try #require(sounds.duration(of: .conclusion))
        #expect(conclusion > 0.150, "the game settling is not another tock")
        #expect(conclusion <= 0.450)
    }

    @Test("Each sound names its own asset")
    func resourceNamesAreDistinct() {
        let names = Set(Feedback.Sound.allCases.map(\.resource))
        #expect(names.count == Feedback.Sound.allCases.count)
        #expect(names.allSatisfy { $0.hasPrefix("board-") })
    }
}
